os:
  - Visual Studio 2015
  
platform: x64
  - x64
  
branches:
  only:
    - master
  
install:
  - cinst cmake
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed

configuration:
  - Debug
  
build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
